author:
  email: krassalexs@users.noreply.github.com
  homepage: https://github.com/krassalexs/ha-cityhome-intercom
  name: krassalexs
description: Домофон Город Телеком (CityHome) для Home Assistant
files:
  - custom_components/cityhome_intercom/__init__.py
  - custom_components/cityhome_intercom/api.py
  - custom_components/cityhome_intercom/consts.py
  - custom_components/cityhome_intercom/config_flow.py
  - custom_components/cityhome_intercom/button.py
  - custom_components/cityhome_intercom/camera.py
keywords:
  - cityhome
  - intercom
  - homeassistant
  - home-assistant
  - custom-component
  - python
license: MIT License
name: Домофон Город Телеком (CityHome)